# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backup.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61\x63kup.proto\"\xe4\x01\n\rBackupRequest\x12\x13\n\x0bterminal_id\x18\x01 \x01(\t\x12\x12\n\ncliente_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63lasse_veiculo\x18\x03 \x01(\t\x12\x14\n\x0cnome_veiculo\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x1c\n\x14request_id_pendencia\x18\x07 \x01(\t\x12\x1b\n\x13ip_cliente_pendente\x18\x08 \x01(\t\x12\x1e\n\x16porta_cliente_pendente\x18\t \x01(\t\" \n\x0e\x42\x61\x63kupResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"o\n\x14QueryPendingRequests\x12\x1f\n\x17terminal_id_responsavel\x18\x01 \x01(\t\x12\x1f\n\x17\x63lasse_veiculo_desejada\x18\x02 \x01(\t\x12\x15\n\rapenas_ativas\x18\x03 \x01(\x08\"\xce\x01\n\x12PendingRequestInfo\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\ncliente_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63lasse_veiculo\x18\x03 \x01(\t\x12\x12\n\nip_cliente\x18\x04 \x01(\t\x12\x15\n\rporta_cliente\x18\x05 \x01(\t\x12(\n terminal_id_original_responsavel\x18\x06 \x01(\t\x12#\n\x1btimestamp_entrada_pendencia\x18\x07 \x01(\t\"V\n\x14QueryPendingResponse\x12\'\n\npendencias\x18\x01 \x03(\x0b\x32\x13.PendingRequestInfo\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x8b\x01\n\rBackupService\x12\x35\n\x12RegistrarTransacao\x12\x0e.BackupRequest\x1a\x0f.BackupResponse\x12\x43\n\x13\x43onsultarPendencias\x12\x15.QueryPendingRequests\x1a\x15.QueryPendingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKUPREQUEST']._serialized_start=17
  _globals['_BACKUPREQUEST']._serialized_end=245
  _globals['_BACKUPRESPONSE']._serialized_start=247
  _globals['_BACKUPRESPONSE']._serialized_end=279
  _globals['_QUERYPENDINGREQUESTS']._serialized_start=281
  _globals['_QUERYPENDINGREQUESTS']._serialized_end=392
  _globals['_PENDINGREQUESTINFO']._serialized_start=395
  _globals['_PENDINGREQUESTINFO']._serialized_end=601
  _globals['_QUERYPENDINGRESPONSE']._serialized_start=603
  _globals['_QUERYPENDINGRESPONSE']._serialized_end=689
  _globals['_BACKUPSERVICE']._serialized_start=692
  _globals['_BACKUPSERVICE']._serialized_end=831
# @@protoc_insertion_point(module_scope)
