# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\"(\n\x15RentCarConfirmRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x16RentCarConfirmResponse\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32[\n\x0e\x43lient_Waiting\x12I\n\x14RentACarConfirmation\x12\x16.RentCarConfirmRequest\x1a\x17.RentCarConfirmResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENTCARCONFIRMREQUEST']._serialized_start=16
  _globals['_RENTCARCONFIRMREQUEST']._serialized_end=56
  _globals['_RENTCARCONFIRMRESPONSE']._serialized_start=58
  _globals['_RENTCARCONFIRMRESPONSE']._serialized_end=99
  _globals['_CLIENT_WAITING']._serialized_start=101
  _globals['_CLIENT_WAITING']._serialized_end=192
# @@protoc_insertion_point(module_scope)
