# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guiche_info.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'guiche_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11guiche_info.proto\"\x1b\n\x0bInfoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tInfoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty25\n\x0bInformation\x12&\n\x0eTerminalOnLine\x12\x06.Empty\x1a\n.InfoReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guiche_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFOREQUEST']._serialized_start=21
  _globals['_INFOREQUEST']._serialized_end=48
  _globals['_INFOREPLY']._serialized_start=50
  _globals['_INFOREPLY']._serialized_end=78
  _globals['_EMPTY']._serialized_start=80
  _globals['_EMPTY']._serialized_end=87
  _globals['_INFORMATION']._serialized_start=89
  _globals['_INFORMATION']._serialized_end=142
# @@protoc_insertion_point(module_scope)
