# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import terminal_pb2 as terminal__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in terminal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TerminalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RentACar = channel.unary_unary(
                '/Terminal/RentACar',
                request_serializer=terminal__pb2.RentCarRequest.SerializeToString,
                response_deserializer=terminal__pb2.RentCarResponse.FromString,
                _registered_method=True)
        self.ReturnACar = channel.unary_unary(
                '/Terminal/ReturnACar',
                request_serializer=terminal__pb2.ReturnCarRequest.SerializeToString,
                response_deserializer=terminal__pb2.ReturnCarResponse.FromString,
                _registered_method=True)
        self.CheckPending = channel.unary_unary(
                '/Terminal/CheckPending',
                request_serializer=terminal__pb2.CheckPendingStatusRequest.SerializeToString,
                response_deserializer=terminal__pb2.CheckPendingStatusResponse.FromString,
                _registered_method=True)
        self.GetAvailableVehicles = channel.unary_unary(
                '/Terminal/GetAvailableVehicles',
                request_serializer=terminal__pb2.GetAvailableVehiclesRequest.SerializeToString,
                response_deserializer=terminal__pb2.GetAvailableVehiclesResponse.FromString,
                _registered_method=True)


class TerminalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RentACar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnACar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPending(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableVehicles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RentACar': grpc.unary_unary_rpc_method_handler(
                    servicer.RentACar,
                    request_deserializer=terminal__pb2.RentCarRequest.FromString,
                    response_serializer=terminal__pb2.RentCarResponse.SerializeToString,
            ),
            'ReturnACar': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnACar,
                    request_deserializer=terminal__pb2.ReturnCarRequest.FromString,
                    response_serializer=terminal__pb2.ReturnCarResponse.SerializeToString,
            ),
            'CheckPending': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPending,
                    request_deserializer=terminal__pb2.CheckPendingStatusRequest.FromString,
                    response_serializer=terminal__pb2.CheckPendingStatusResponse.SerializeToString,
            ),
            'GetAvailableVehicles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableVehicles,
                    request_deserializer=terminal__pb2.GetAvailableVehiclesRequest.FromString,
                    response_serializer=terminal__pb2.GetAvailableVehiclesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Terminal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Terminal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Terminal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RentACar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Terminal/RentACar',
            terminal__pb2.RentCarRequest.SerializeToString,
            terminal__pb2.RentCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnACar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Terminal/ReturnACar',
            terminal__pb2.ReturnCarRequest.SerializeToString,
            terminal__pb2.ReturnCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPending(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Terminal/CheckPending',
            terminal__pb2.CheckPendingStatusRequest.SerializeToString,
            terminal__pb2.CheckPendingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableVehicles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Terminal/GetAvailableVehicles',
            terminal__pb2.GetAvailableVehiclesRequest.SerializeToString,
            terminal__pb2.GetAvailableVehiclesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CallbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveCallback = channel.unary_unary(
                '/CallbackService/ReceiveCallback',
                request_serializer=terminal__pb2.CallbackMessage.SerializeToString,
                response_deserializer=terminal__pb2.CallbackResponse.FromString,
                _registered_method=True)


class CallbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveCallback,
                    request_deserializer=terminal__pb2.CallbackMessage.FromString,
                    response_serializer=terminal__pb2.CallbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CallbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CallbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CallbackService/ReceiveCallback',
            terminal__pb2.CallbackMessage.SerializeToString,
            terminal__pb2.CallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
